### ISSUE TITLE
Crash when attempting to load world - Forge + Sinytra 1.20.1

### ISSUE THREAD

**Issue by CrazedslawDev** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#13]
```
Encountered an unexpected exception
java.lang.ClassCastException: class com.mrcrayfish.furniture.refurbished.mail.DeliveryService cannot be cast to class com.mrcrayfish.mightymail.mail.DeliveryService (com.mrcrayfish.furniture.refurbished.mail.DeliveryService is in module refurbished_furniture@1.0.3 of loader 'TRANSFORMER' @7ea91c39; com.mrcrayfish.mightymail.mail.DeliveryService is in module mighty_mail@1.0.14 of loader 'TRANSFORMER' @7ea91c39)
	at TRANSFORMER/mighty_mail@1.0.14/com.mrcrayfish.mightymail.mail.DeliveryService.get(DeliveryService.java:51)
	at TRANSFORMER/mighty_mail@1.0.14/com.mrcrayfish.mightymail.Bootstrap.lambda$init$0(Bootstrap.java:24)
	at TRANSFORMER/framework@0.7.6/com.mrcrayfish.framework.api.event.TickEvents.lambda$static$4(TickEvents.java:19)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/framework@0.7.6/com.mrcrayfish.framework.api.event.TickEvents.lambda$static$5(TickEvents.java:19)
	at TRANSFORMER/framework@0.7.6/com.mrcrayfish.framework.event.ForgeEvents.onServerTick(ForgeEvents.java:32)
	at TRANSFORMER/framework@0.7.6/com.mrcrayfish.framework.event.__ForgeEvents_onServerTick_ServerTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.5/net.minecraftforge.event.ForgeEventFactory.onPreServerTick(ForgeEventFactory.java:945)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:812)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
	
**This error happens anytime I attempt to load into a world post-installation of the mod. Mod list below:** 

[Mod List](https://pastebin.com/tbBse8AX)

**Comment by MrCrayfish** [comment]
Mighty Mail is not compatible since it's already included in the refurbished furniture mod.
