### ISSUE TITLE
The game crash when using workbench

### ISSUE THREAD

**Issue by Gordonzxr** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#25]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-08-24 00:27:39
Description: Exception in server tick loop

java.lang.IllegalAccessError: class com.mrcrayfish.framework.platform.NeoForgeNetworkHelper tried to access private field net.minecraft.server.level.ServerPlayer.containerCounter (com.mrcrayfish.framework.platform.NeoForgeNetworkHelper is in module framework@0.9.0 of loader 'TRANSFORMER' @6baf25d7; net.minecraft.server.level.ServerPlayer is in module minecraft@1.21 of loader 'TRANSFORMER' @6baf25d7)
	at TRANSFORMER/framework@0.9.0/com.mrcrayfish.framework.platform.NeoForgeNetworkHelper.openMenuWithData(NeoForgeNetworkHelper.java:33) ~[framework-neoforge-1.21-0.9.0.jar%23204!/:?] {re:classloading}
	at TRANSFORMER/framework@0.9.0/com.mrcrayfish.framework.api.FrameworkAPI.openMenuWithData(FrameworkAPI.java:57) ~[framework-neoforge-1.21-0.9.0.jar%23204!/:?] {re:classloading}
	at TRANSFORMER/refurbished_furniture@1.0.6/com.mrcrayfish.furniture.refurbished.block.WorkbenchBlock.useWithoutItem(WorkbenchBlock.java:67) ~[refurbished_furniture-neoforge-1.21-1.0.6.jar%23217!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.useWithoutItem(BlockBehaviour.java:757) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:370) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:computing_frames,re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1122) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:42) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:10) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:27) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:mixin,re:computing_frames,re:classloading}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:872) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:170) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:855) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:849) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:821) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:826) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:712) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21-20240613.152323-srg.jar%23199!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 445757512 bytes (425 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics  
	Identifier: AuthenticAMD Family 25 Model 116 Stepping 1
	Microarchitecture: Zen 3
	Frequency (GHz): 3.29
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) 780M
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.11021.1011
	Memory slot #0 capacity (MiB): 4096.00
	Memory slot #0 clockSpeed (GHz): 6.40
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 4096.00
	Memory slot #1 clockSpeed (GHz): 6.40
	Memory slot #1 type: Unknown
	Memory slot #2 capacity (MiB): 4096.00
	Memory slot #2 clockSpeed (GHz): 6.40
	Memory slot #2 type: Unknown
	Memory slot #3 capacity (MiB): 4096.00
	Memory slot #3 clockSpeed (GHz): 6.40
	Memory slot #3 type: Unknown
	Virtual memory max (MiB): 33505.36
	Virtual memory used (MiB): 22056.21
	Swap memory total (MiB): 18432.00
	Swap memory used (MiB): 882.32
	Space in storage for jna.tmpdir (MiB): available: 246083.19, total: 486109.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 246083.19, total: 486109.00
	Space in storage for io.netty.native.workdir (MiB): available: 246083.19, total: 486109.00
	Space in storage for java.io.tmpdir (MiB): available: 246083.19, total: 486109.00
	Space in storage for workdir (MiB): available: 246083.19, total: 486109.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Gordonzxr930818'/20, l='ServerLevel[新的世界]', x=-8659.36, y=70.00, z=1391.86]]
	Active Data Packs: vanilla, mod_data, mod/handcrafted, mod/kuma_api (incompatible), mod/resourcefullib, mod/mcwroofs (incompatible), mod/mcwdoors (incompatible), mod/mcwfences (incompatible), mod/balm (incompatible), mod/refurbished_furniture (incompatible), mod/jei (incompatible), mod/simplylight (incompatible), mod/framework (incompatible), mod/mekanism, mod/mekanismtools, mod/mekanismadditions, mod/mekanismgenerators, mod/car (incompatible), mod/luckytntmod, mod/luckytntlib, mod/cookingforblockheads (incompatible), mod/neoforge, mod/mcwlights (incompatible)
	Available Data Packs: bundle, trade_rebalance, vanilla, mod/balm (incompatible), mod/car (incompatible), mod/cookingforblockheads (incompatible), mod/framework (incompatible), mod/handcrafted, mod/jei (incompatible), mod/kuma_api (incompatible), mod/luckytntlib, mod/luckytntmod, mod/mcwdoors (incompatible), mod/mcwfences (incompatible), mod/mcwlights (incompatible), mod/mcwroofs (incompatible), mod/mekanism, mod/mekanismadditions, mod/mekanismgenerators, mod/mekanismtools, mod/neoforge, mod/refurbished_furniture (incompatible), mod/resourcefullib, mod/simplylight (incompatible), mod_data
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -4235921392673757459
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'neoforge'; Server brand changed to 'neoforge'
	Launched Version: neoforge-21.0.91-beta
	ModLauncher: 11.0.4+main.d2e20e43
	ModLauncher launch target: forgeclient
	ModLauncher services: 
		sponge-mixin-0.14.0+mixin.0.8.6.jar mixin PLUGINSERVICE 
		loader-4.0.18.jar slf4jfixer PLUGINSERVICE 
		loader-4.0.18.jar runtime_enum_extender PLUGINSERVICE 
		at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE 
		loader-4.0.18.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		javafml@4.0
		lowcodefml@4.0
		minecraft@4.0
	Mod List: 
		client-1.21-20240613.152323-srg.jar               |Minecraft                     |minecraft                     |1.21                |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		handcrafted-neoforge-1.21-4.0.1.jar               |Handcrafted                   |handcrafted                   |4.0.1               |Manifest: NOSIGNATURE
		kuma-api-neoforge-21.0.4+1.21.jar                 |KumaAPI                       |kuma_api                      |21.0.4              |Manifest: NOSIGNATURE
		resourcefullib-neoforge-1.21-3.0.9.jar            |Resourceful Lib               |resourcefullib                |3.0.9               |Manifest: NOSIGNATURE
		mcw-roofs-2.3.1-mc1.21neoforge.jar                |Macaw's Roofs                 |mcwroofs                      |2.3.1               |Manifest: NOSIGNATURE
		mcw-doors-1.1.1neoforge-mc1.21.jar                |Macaw's Doors                 |mcwdoors                      |1.1.1               |Manifest: NOSIGNATURE
		mcw-fences-1.1.2-mc1.21neoforge.jar               |Macaw's Fences and Walls      |mcwfences                     |1.1.2               |Manifest: NOSIGNATURE
		balm-neoforge-1.21-21.0.14-all.jar                |Balm                          |balm                          |21.0.14             |Manifest: NOSIGNATURE
		refurbished_furniture-neoforge-1.21-1.0.6.jar     |MrCrayfish's Furniture Mod: Re|refurbished_furniture         |1.0.6               |Manifest: NOSIGNATURE
		jei-1.21-neoforge-19.5.0.38.jar                   |Just Enough Items             |jei                           |19.5.0.38           |Manifest: NOSIGNATURE
		simplylight-1.4.6+1.21-b53.jar                    |Simply Light                  |simplylight                   |1.4.6+1.21-b53      |Manifest: NOSIGNATURE
		framework-neoforge-1.21-0.9.0.jar                 |Framework                     |framework                     |0.9.0               |Manifest: NOSIGNATURE
		Mekanism-1.21-10.6.5.52.jar                       |Mekanism                      |mekanism                      |10.6.5              |Manifest: NOSIGNATURE
		MekanismTools-1.21-10.6.5.52.jar                  |Mekanism: Tools               |mekanismtools                 |10.6.5              |Manifest: NOSIGNATURE
		MekanismAdditions-1.21-10.6.5.52.jar              |Mekanism: Additions           |mekanismadditions             |10.6.5              |Manifest: NOSIGNATURE
		MekanismGenerators-1.21-10.6.5.52.jar             |Mekanism: Generators          |mekanismgenerators            |10.6.5              |Manifest: NOSIGNATURE
		car-neoforge-1.21.1-1.0.24.jar                    |Ultimate Car Mod              |car                           |1.21.1-1.0.24       |Manifest: NOSIGNATURE
		neo-luckytntmod-1.21-6.0.jar                      |Lucky TNT Mod                 |luckytntmod                   |6.0                 |Manifest: NOSIGNATURE
		neo-luckytntlib-1.21-21.0.78.2.jar                |Lucky TNT Lib                 |luckytntlib                   |21.0.78.2           |Manifest: NOSIGNATURE
		cookingforblockheads-neoforge-1.21-21.0.4.jar     |Cooking for Blockheads        |cookingforblockheads          |21.0.4              |Manifest: NOSIGNATURE
		neoforge-21.0.91-beta-universal.jar               |NeoForge                      |neoforge                      |21.0.91-beta        |Manifest: NOSIGNATURE
		mcw-lights-1.1.1-mc1.21neoforge.jar               |Macaw's Lights and Lamps      |mcwlights                     |1.1.1               |Manifest: NOSIGNATURE
	Crash Report UUID: 4dfc3bb5-efc6-49f7-a028-42736afa12a7
	FML: 4.0.18
	NeoForge: 21.0.91-beta

**Comment by MrCrayfish** [comment]
This is now fixed. You'll need to update Framework
