### ISSUE TITLE
Game Crash Whilst ticking player

### ISSUE THREAD

**Issue by Anannsul** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#51]
```
---- Minecraft Crash Report ----
// You're mean.

Time: 2024-10-06 21:49:39
Description: Ticking player

java.lang.ClassCastException: class net.minecraft.server.level.ServerLevel cannot be cast to class com.mrcrayfish.furniture.refurbished.electricity.LinkManager$Access (net.minecraft.server.level.ServerLevel is in module minecraft@1.20.6 of loader 'TRANSFORMER' @50211483; com.mrcrayfish.furniture.refurbished.electricity.LinkManager$Access is in module refurbished_furniture@1.0.6 of loader 'TRANSFORMER' @50211483)
	at TRANSFORMER/refurbished_furniture@1.0.6/com.mrcrayfish.furniture.refurbished.electricity.LinkManager.get(LinkManager.java:34) ~[refurbished_furniture-forge-1.20.6-1.0.6.jar!/:1.20.6-1.0.6] {re:classloading}
	at TRANSFORMER/refurbished_furniture@1.0.6/com.mrcrayfish.furniture.refurbished.Bootstrap.lambda$registerFrameworkEvents$2(Bootstrap.java:80) ~[refurbished_furniture-forge-1.20.6-1.0.6.jar!/:1.20.6-1.0.6] {re:classloading}
	at TRANSFORMER/framework@0.8.13/com.mrcrayfish.framework.api.event.TickEvents.lambda$static$19(TickEvents.java:39) ~[framework-forge-1.20.6-0.8.13.jar!/:1.20.6-0.8.13] {re:classloading}
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?] {}
	at TRANSFORMER/framework@0.8.13/com.mrcrayfish.framework.api.event.TickEvents.lambda$static$20(TickEvents.java:39) ~[framework-forge-1.20.6-0.8.13.jar!/:1.20.6-0.8.13] {re:classloading}
	at TRANSFORMER/framework@0.8.13/com.mrcrayfish.framework.event.ForgeEvents.onPlayerTick(ForgeEvents.java:163) ~[framework-forge-1.20.6-0.8.13.jar!/:1.20.6-0.8.13] {re:classloading}
	at TRANSFORMER/framework@0.8.13/com.mrcrayfish.framework.event.__ForgeEvents_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[framework-forge-1.20.6-0.8.13.jar!/:1.20.6-0.8.13] {re:classloading,pl:eventbus:B}
	at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:48) ~[eventbus-6.2.6.jar!/:?] {}
	at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:304) ~[eventbus-6.2.6.jar!/:?] {}
	at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:290) ~[eventbus-6.2.6.jar!/:?] {}
	at TRANSFORMER/forge@50.1.0/net.minecraftforge.event.ForgeEventFactory.post(ForgeEventFactory.java:227) ~[forge-1.20.6-50.1.0-universal.jar!/:?] {re:classloading}
	at TRANSFORMER/forge@50.1.0/net.minecraftforge.event.ForgeEventFactory.onPlayerPostTick(ForgeEventFactory.java:814) ~[forge-1.20.6-50.1.0-universal.jar!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.world.entity.player.Player.tick(Player.java:316) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:545) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:259) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.network.Connection.tick(Connection.java:398) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:149) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1011) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:887) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:136) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading,xf:OptiFine:default}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:695) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:261) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mods: 
	MrCrayfish's Furniture Mod: Refurbished (refurbished_furniture), Version: 1.0.6
		Issue tracker URL: https://github.com/MrCrayfish/MrCrayfishFurnitureMod-Refurbished/issues
		at TRANSFORMER/refurbished_furniture@1.0.6/com.mrcrayfish.furniture.refurbished.electricity.LinkManager.get(LinkManager.java:34)

	Framework (framework), Version: 0.8.13
		at TRANSFORMER/framework@0.8.13/com.mrcrayfish.framework.api.event.TickEvents.lambda$static$19(TickEvents.java:39)
Stacktrace:
	at TRANSFORMER/refurbished_furniture@1.0.6/com.mrcrayfish.furniture.refurbished.electricity.LinkManager.get(LinkManager.java:34) ~[refurbished_furniture-forge-1.20.6-1.0.6.jar!/:1.20.6-1.0.6] {re:classloading}
	at TRANSFORMER/refurbished_furniture@1.0.6/com.mrcrayfish.furniture.refurbished.Bootstrap.lambda$registerFrameworkEvents$2(Bootstrap.java:80) ~[refurbished_furniture-forge-1.20.6-1.0.6.jar!/:1.20.6-1.0.6] {re:classloading}
	at TRANSFORMER/framework@0.8.13/com.mrcrayfish.framework.api.event.TickEvents.lambda$static$19(TickEvents.java:39) ~[framework-forge-1.20.6-0.8.13.jar!/:1.20.6-0.8.13] {re:classloading}
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?] {}
	at TRANSFORMER/framework@0.8.13/com.mrcrayfish.framework.api.event.TickEvents.lambda$static$20(TickEvents.java:39) ~[framework-forge-1.20.6-0.8.13.jar!/:1.20.6-0.8.13] {re:classloading}
	at TRANSFORMER/framework@0.8.13/com.mrcrayfish.framework.event.ForgeEvents.onPlayerTick(ForgeEvents.java:163) ~[framework-forge-1.20.6-0.8.13.jar!/:1.20.6-0.8.13] {re:classloading}
	at TRANSFORMER/framework@0.8.13/com.mrcrayfish.framework.event.__ForgeEvents_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[framework-forge-1.20.6-0.8.13.jar!/:1.20.6-0.8.13] {re:classloading,pl:eventbus:B}
	at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:48) ~[eventbus-6.2.6.jar!/:?] {}
	at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:304) ~[eventbus-6.2.6.jar!/:?] {}
	at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:290) ~[eventbus-6.2.6.jar!/:?] {}
	at TRANSFORMER/forge@50.1.0/net.minecraftforge.event.ForgeEventFactory.post(ForgeEventFactory.java:227) ~[forge-1.20.6-50.1.0-universal.jar!/:?] {re:classloading}
	at TRANSFORMER/forge@50.1.0/net.minecraftforge.event.ForgeEventFactory.onPlayerPostTick(ForgeEventFactory.java:814) ~[forge-1.20.6-50.1.0-universal.jar!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.world.entity.player.Player.tick(Player.java:316) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading,pl:accesstransformer:B}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.server.level.ServerPlayer)
	Entity ID: 25
	Entity Name: Anannsul
	Entity's Exact location: 74.09, 71.00, -56.82
	Entity's Block location: World: (74,71,-57), Section: (at 10,7,7 in 4,4,-4; chunk contains blocks 64,-64,-64 to 79,319,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:545) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:259) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.network.Connection.tick(Connection.java:398) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:149) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1011) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:887) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:136) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading,xf:OptiFine:default}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:695) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading,pl:accesstransformer:B}
	at TRANSFORMER/minecraft@1.20.6/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:261) ~[forge-1.20.6-50.1.0-client.jar!/:?] {re:classloading,pl:accesstransformer:B}
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.20.6
	Minecraft Version ID: 1.20.6
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 629145600 bytes (600 MiB) / 1734344704 bytes (1654 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12650H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.69
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 4050 Laptop GPU
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MB): 6141.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6590
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 31.0.101.5081
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 29400.05
	Virtual memory used (MB): 23085.50
	Swap memory total (MB): 13312.00
	Swap memory used (MB): 1298.49
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Anannsul'/25, l='ServerLevel[We're All Mad Here]', x=74.09, y=71.00, z=-56.82]]
	Active Data Packs: vanilla, mod:fullbrightnesstoggle, mod:forge (incompatible), mod:burgermod, mod:more_food (incompatible), mod:corail_woodcutter (incompatible), mod:chas (incompatible), mod:collective, mod:treeharvester, mod:jei (incompatible), mod:infinite_bundle, mod:mcwfurnitures (incompatible), mod:refurbished_furniture (incompatible), mod:framework (incompatible)
	Available Data Packs: bundle, mod:burgermod, mod:chas (incompatible), mod:collective, mod:corail_woodcutter (incompatible), mod:forge (incompatible), mod:framework (incompatible), mod:fullbrightnesstoggle, mod:infinite_bundle, mod:jei (incompatible), mod:mcwfurnitures (incompatible), mod:more_food (incompatible), mod:refurbished_furniture (incompatible), mod:treeharvester, trade_rebalance, update_1_21, vanilla
	Enabled Feature Flags: minecraft:bundle, minecraft:vanilla
	World Generation: Experimental
	World Seed: -869344507
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: forge-50.1.0
	OptiFine Version: OptiFine_1.20.6_HD_U_J1_pre18
	OptiFine Build: 20240927-190741
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildur's Vibrant Shaders v1.52 Medium.zip
	OpenGlVersion: 4.6.0 NVIDIA 565.90
	OpenGlRenderer: NVIDIA GeForce RTX 4050 Laptop GPU/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16
	ModLauncher: 10.2.1
	ModLauncher launch target: forge_client
	ModLauncher naming: mcp
	ModLauncher services: 
		/ slf4jfixer PLUGINSERVICE 
		/ runtimedistcleaner PLUGINSERVICE 
		/ runtime_enum_extender PLUGINSERVICE 
		/ object_holder_definalize PLUGINSERVICE 
		/ capability_token_subclass PLUGINSERVICE 
		/ accesstransformer PLUGINSERVICE 
		/ eventbus PLUGINSERVICE 
		/ mixin PLUGINSERVICE 
		/ OptiFine TRANSFORMATIONSERVICE 
		/ fml TRANSFORMATIONSERVICE 
		/ mixin TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@50
		javafml@50.1.0
	Mod List: 
		forge-1.20.6-50.1.0-client.jar                    |Minecraft                     |minecraft                     |1.20.6              |DONE      |Manifest: NOSIGNATURE
		fullbrightnesstoggle-1.20.6-4.2.jar               |Full Brightness Toggle        |fullbrightnesstoggle          |4.2                 |DONE      |Manifest: NOSIGNATURE
		InfiniteStorageBundle-v8.jar                      |Infinite Storage Bundle       |infinite_bundle               |8                   |DONE      |Manifest: NOSIGNATURE
		burgermod-2.9.4-1.20.6.jar                        |Burger Mod                    |burgermod                     |2.9.4               |DONE      |Manifest: NOSIGNATURE
		treeharvester-1.20.6-9.1.jar                      |Tree Harvester                |treeharvester                 |9.1                 |DONE      |Manifest: NOSIGNATURE
		mcw-furniture-3.3.0-mc1.20.6forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.3.0               |DONE      |Manifest: NOSIGNATURE
		refurbished_furniture-forge-1.20.6-1.0.6.jar      |MrCrayfish's Furniture Mod: Re|refurbished_furniture         |1.0.6               |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		jei-1.20.6-forge-18.0.0.65.jar                    |Just Enough Items             |jei                           |18.0.0.65           |DONE      |Manifest: NOSIGNATURE
		framework-forge-1.20.6-0.8.13.jar                 |Framework                     |framework                     |0.8.13              |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		forge-1.20.6-50.1.0-universal.jar                 |Forge                         |forge                         |50.1.0              |DONE      |Manifest: NOSIGNATURE
		more_food-forge-2.0.0+1.20.6.jar                  |More Food                     |more_food                     |2.0.0+1.20.6        |DONE      |Manifest: NOSIGNATURE
		corail_woodcutter-1.20.6-3.3.0.jar                |Corail Woodcutter             |corail_woodcutter             |3.3.0               |DONE      |Manifest: NOSIGNATURE
		CHA-S-1.20-forge.jar                              |CHA&S - Craftable Horse Armour|chas                          |1.20                |DONE      |Manifest: NOSIGNATURE
		collective-1.20.6-7.84.jar                        |Collective                    |collective                    |7.84                |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 244ca86f-6990-4f2b-b973-a9e65a3542d0
	FML: 0.0
	Forge: net.minecraftforge:50.1.0
	```

**Comment by MrCrayfish** [comment]
The 1.20.6 version is no longer supported. Please downgrade to 1.20.1 or update to 1.21.1 or above.
