### ISSUE TITLE
ATM10 Crash when swaping away from Creative Inventory

### ISSUE THREAD

**Issue by shartte** [MrCrayfish/MrCrayfishFurnitureMod-Refurbished#76]
This happens when I try to open an AE2 guidebook from within the creative inventory. It seems something is causing an event to be emitted for rendering the old screen after a close event was sent to you (?)

```
Forge[15:17:16] [Render thread/ERROR] [ne.ne.bu.EventBus/EVENTBUS]: Exception caught during firing event: Cannot read field "visible" because "tab" is null
	Index: 10
	Listeners:
		0: net.neoforged.bus.EventListenerFactory$renderPostHighest/0x00000295c81c5000@6ca2a869
		1: net.neoforged.bus.EventListenerFactory$eventDrawScreenEvent/0x00000295c4779000@24d838a7
		2: net.neoforged.bus.EventListenerFactory$onGuiRender/0x00000295c27d0000@2e912435
		3: net.p3pp3rf1y.sophisticatedcore.client.ClientEventHandler$$Lambda/0x00000295c2a4c8f8@31592a2c
		4: net.blay09.mods.balm.neoforge.event.NeoForgeBalmClientEvents$$Lambda/0x00000295c331c8f8@562046c8
		5: it.zerono.mods.zerocore.internal.proxy.ClientProxy$$Lambda/0x00000295c3b91db0@7527ee0d
		6: snownee.jade.util.ClientProxy$$Lambda/0x00000295c5024148@4d9f5260
		7: net.neoforged.bus.EventListenerFactory$onGuiDrawPost/0x00000295c5c6c800@7f5565c1
		8: net.neoforged.bus.EventListenerFactory$screenPostDraw/0x00000295c5d79000@6cd7ba2
		9: net.neoforged.bus.EventListenerFactory$onDrawScreen/0x00000295c815c800@633576dc
		10: net.neoforged.bus.EventListenerFactory$onScreenRenderPost/0x00000295c8168c00@44a24603
		11: net.neoforged.bus.EventListenerFactory$drawAnvilCostBlob/0x00000295c8178800@108d583b
		12: net.neoforged.bus.EventListenerFactory$render/0x00000295c8185400@7d7021e3
		13: me.frankv.jmi.JMINeoForge$$Lambda/0x00000295c81c8ea8@1c571ef4
		14: mezz.jei.core.util.WeakConsumer@430ba0a0
		15: net.neoforged.bus.EventListenerFactory$renderPostLowest/0x00000295c81cc000@353b2b07
java.lang.NullPointerException: Cannot read field "visible" because "tab" is null
	at TRANSFORMER/refurbished_furniture@1.0.8/com.mrcrayfish.furniture.refurbished.client.CreativeFilters.drawFilterTabTooltips(CreativeFilters.java:256)
	at TRANSFORMER/refurbished_furniture@1.0.8/com.mrcrayfish.furniture.refurbished.client.CreativeFilters.lambda$new$3(CreativeFilters.java:112)
	at TRANSFORMER/framework@0.9.4/com.mrcrayfish.framework.api.event.ScreenEvents.lambda$static$9(ScreenEvents.java:25)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at TRANSFORMER/framework@0.9.4/com.mrcrayfish.framework.api.event.ScreenEvents.lambda$static$10(ScreenEvents.java:25)
	at TRANSFORMER/framework@0.9.4/com.mrcrayfish.framework.client.ClientNeoForgeEvents.onScreenRenderPost(ClientNeoForgeEvents.java:102)
	at net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350)
	at net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315)
	at TRANSFORMER/neoforge@21.1.90/net.neoforged.neoforge.client.ClientHooks.drawScreenInternal(ClientHooks.java:430)
	at TRANSFORMER/neoforge@21.1.90/net.neoforged.neoforge.client.ClientHooks.drawScreen(ClientHooks.java:423)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.mixinextras$bridge$drawScreen$247(GameRenderer.java)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.wrapOperation$cdd000$konkrete$wrapRenderScreen_Konkrete(GameRenderer.java:5795)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1092)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1195)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at fml_loader@4.0.46-startup-experiments/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:139)
	at fml_loader@4.0.46-startup-experiments/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:130)
	at fml_loader@4.0.46-startup-experiments/net.neoforged.fml.loading.targets.NeoForgeClientLaunchHandler.runService(NeoForgeClientLaunchHandler.java:39)
	at fml_loader@4.0.46-startup-experiments/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:124)
	at fml_loader@4.0.46-startup-experiments/net.neoforged.fml.loading.FMLLoader.startup(FMLLoader.java:339)
	at net.neoforged.fmlstartup.Startup.run(Startup.java:218)
	at net.neoforged.fmlstartup.Startup.main(Startup.java:48)

Forge[15:17:16] [Render thread/ERROR] [minecraft/Minecraft]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1120) ~[client-1.21.1-20240808.144430-srg.jar%230!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:auroras.mixins.json:client.GameRendererMixin from mod (unknown),pl:mixin:APP:mixins.iris.json:GameRendererAccessor from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinGameRenderer from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinModelViewBobbing from mod (unknown),pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:tombstone.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:sodium-common.mixins.json:features.gui.hooks.console.GameRendererMixin from mod (unknown),pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod (unknown),pl:mixin:APP:konkrete.neoforge.mixins.json:client.MixinGameRenderer from mod (unknown),pl:mixin:APP:darkmodeeverywhere.mixins.json:GameRenderMixin from mod (unknown),pl:mixin:APP:mixins.artifacts.common.json:ability.nightvision.client.GameRendererMixin from mod (unknown),pl:mixin:APP:justzoom.mixins.json:client.MixinGameRenderer from mod (unknown),pl:mixin:APP:rarcompat.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:flickerfix.mixins.json:MixinGameRenderer from mod (unknown),pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer from mod (unknown),pl:mixin:APP:eternal_starlight-common.mixins.json:client.GameRendererMixin from mod (unknown),pl:mixin:APP:ars_nouveau.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:kubejs.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinGameRenderer_NightVisionCompat from mod (unknown),pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin from mod (unknown),pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1195) ~[client-1.21.1-20240808.144430-srg.jar%230!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mffs.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod (unknown),pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod (unknown),pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod (unknown),pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod (unknown),pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinMinecraft_Images from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinMinecraft_Keybinds from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinMinecraft_PipelineManagement from mod (unknown),pl:mixin:APP:supplementaries-common.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:omega-config.mixins.json:ClientMixin from mod (unknown),pl:mixin:APP:the_bumblezone-common.mixins.json:client.MinecraftMixin from mod (unknown),pl:mixin:APP:sodium-common.mixins.json:core.MinecraftMixin from mod (unknown),pl:mixin:APP:sodium-neoforge.mixins.json:platform.neoforge.EntrypointMixin from mod (unknown),pl:mixin:APP:alltheleaks.mixins.json:main.MinecraftMixin from mod (unknown),pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinMinecraftClient from mod (unknown),pl:mixin:APP:glassential.mixins.json:MixinMinecraft from mod (unknown),pl:mixin:APP:prism.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:bookshelf.mixins.json:access.client.AccessorMinecraft from mod (unknown),pl:mixin:APP:konkrete.mixins.json:client.MixinMinecraft from mod (unknown),pl:mixin:APP:bridgingmod.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:APP:monolib.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:irons_spellbooks.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:sodium-extra.mixins.json:core.MixinMinecraftClient from mod (unknown),pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor from mod (unknown),pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:eternal_starlight-common.mixins.json:client.MinecraftMixin from mod (unknown),pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod (unknown),pl:mixin:APP:mekanismcovers.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess from mod (unknown),pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinMinecraft from mod (unknown),pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin from mod (unknown),pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod (unknown),pl:mixin:APP:kubejs.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:APP:neoauth.mixins.json:MinecraftClientAccessor from mod (unknown),pl:mixin:APP:journeymap.mixins.json:client.MinecraftMixin from mod (unknown),pl:mixin:APP:moonlight-common.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod (unknown),pl:mixin:APP:ae2wtlib.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:forbidden_arcanus.mixins.json:client.MinecraftMixin from mod (unknown),pl:mixin:APP:iceberg.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:yacl.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin from mod (unknown),pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin from mod (unknown),pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21.1-20240808.144430-srg.jar%230!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mffs.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod (unknown),pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod (unknown),pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod (unknown),pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod (unknown),pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinMinecraft_Images from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinMinecraft_Keybinds from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinMinecraft_PipelineManagement from mod (unknown),pl:mixin:APP:supplementaries-common.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:omega-config.mixins.json:ClientMixin from mod (unknown),pl:mixin:APP:the_bumblezone-common.mixins.json:client.MinecraftMixin from mod (unknown),pl:mixin:APP:sodium-common.mixins.json:core.MinecraftMixin from mod (unknown),pl:mixin:APP:sodium-neoforge.mixins.json:platform.neoforge.EntrypointMixin from mod (unknown),pl:mixin:APP:alltheleaks.mixins.json:main.MinecraftMixin from mod (unknown),pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinMinecraftClient from mod (unknown),pl:mixin:APP:glassential.mixins.json:MixinMinecraft from mod (unknown),pl:mixin:APP:prism.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:bookshelf.mixins.json:access.client.AccessorMinecraft from mod (unknown),pl:mixin:APP:konkrete.mixins.json:client.MixinMinecraft from mod (unknown),pl:mixin:APP:bridgingmod.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:APP:monolib.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:irons_spellbooks.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:sodium-extra.mixins.json:core.MixinMinecraftClient from mod (unknown),pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor from mod (unknown),pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:eternal_starlight-common.mixins.json:client.MinecraftMixin from mod (unknown),pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod (unknown),pl:mixin:APP:mekanismcovers.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess from mod (unknown),pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinMinecraft from mod (unknown),pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin from mod (unknown),pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod (unknown),pl:mixin:APP:kubejs.mixins.json:MinecraftClientMixin from mod (unknown),pl:mixin:APP:neoauth.mixins.json:MinecraftClientAccessor from mod (unknown),pl:mixin:APP:journeymap.mixins.json:client.MinecraftMixin from mod (unknown),pl:mixin:APP:moonlight-common.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod (unknown),pl:mixin:APP:ae2wtlib.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:forbidden_arcanus.mixins.json:client.MinecraftMixin from mod (unknown),pl:mixin:APP:iceberg.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:yacl.mixins.json:MinecraftMixin from mod (unknown),pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin from mod (unknown),pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin from mod (unknown),pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[1.21.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {re:mixin}
	at fml_loader@4.0.46-startup-experiments/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:139) ~[loader-4.0.46-startup-experiments.jar:?] {}
	at fml_loader@4.0.46-startup-experiments/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:130) ~[loader-4.0.46-startup-experiments.jar:?] {}
	at fml_loader@4.0.46-startup-experiments/net.neoforged.fml.loading.targets.NeoForgeClientLaunchHandler.runService(NeoForgeClientLaunchHandler.java:39) ~[loader-4.0.46-startup-experiments.jar:?] {}
	at fml_loader@4.0.46-startup-experiments/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:124) ~[loader-4.0.46-startup-experiments.jar:?] {}
	at fml_loader@4.0.46-startup-experiments/net.neoforged.fml.loading.FMLLoader.startup(FMLLoader.java:339) ~[loader-4.0.46-startup-experiments.jar:?] {}
	at net.neoforged.fmlstartup.Startup.run(Startup.java:218) [startup-4.0.46-startup-experiments.jar:4.0] {}
	at net.neoforged.fmlstartup.Startup.main(Startup.java:48) [startup-4.0.46-startup-experiments.jar:4.0] {}
Caused by: java.lang.NullPointerException: Cannot read field "visible" because "tab" is null
	at TRANSFORMER/refurbished_furniture@1.0.8/com.mrcrayfish.furniture.refurbished.client.CreativeFilters.drawFilterTabTooltips(CreativeFilters.java:256) ~[refurbished_furniture-neoforge-1.21.1-1.0.8.jar%23303!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/refurbished_furniture@1.0.8/com.mrcrayfish.furniture.refurbished.client.CreativeFilters.lambda$new$3(CreativeFilters.java:112) ~[refurbished_furniture-neoforge-1.21.1-1.0.8.jar%23303!/:?] {re:mixin,re:classloading}
	at TRANSFORMER/framework@0.9.4/com.mrcrayfish.framework.api.event.ScreenEvents.lambda$static$9(ScreenEvents.java:25) ~[framework-neoforge-1.21.1-0.9.4.jar%23133!/:?] {re:classloading}
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?] {re:mixin}
	at TRANSFORMER/framework@0.9.4/com.mrcrayfish.framework.api.event.ScreenEvents.lambda$static$10(ScreenEvents.java:25) ~[framework-neoforge-1.21.1-0.9.4.jar%23133!/:?] {re:classloading}
	at TRANSFORMER/framework@0.9.4/com.mrcrayfish.framework.client.ClientNeoForgeEvents.onScreenRenderPost(ClientNeoForgeEvents.java:102) ~[framework-neoforge-1.21.1-0.9.4.jar%23133!/:?] {re:classloading}
	at net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar:?] {}
	at net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar:?] {}
	at TRANSFORMER/neoforge@21.1.90/net.neoforged.neoforge.client.ClientHooks.drawScreenInternal(ClientHooks.java:430) ~[neoforge-21.1.90-universal.jar%231!/:?] {re:mixin,re:classloading,pl:mixin:APP:sodium-neoforge.mixins.json:platform.neoforge.ClientHooksMixin from mod (unknown),pl:mixin:APP:journeymap.neoforge.mixins.json:client.ClientHooksMixin from mod (unknown),pl:mixin:A}
	at TRANSFORMER/neoforge@21.1.90/net.neoforged.neoforge.client.ClientHooks.drawScreen(ClientHooks.java:423) ~[neoforge-21.1.90-universal.jar%231!/:?] {re:mixin,re:classloading,pl:mixin:APP:sodium-neoforge.mixins.json:platform.neoforge.ClientHooksMixin from mod (unknown),pl:mixin:APP:journeymap.neoforge.mixins.json:client.ClientHooksMixin from mod (unknown),pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.mixinextras$bridge$drawScreen$247(GameRenderer.java) ~[client-1.21.1-20240808.144430-srg.jar%230!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:auroras.mixins.json:client.GameRendererMixin from mod (unknown),pl:mixin:APP:mixins.iris.json:GameRendererAccessor from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinGameRenderer from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinModelViewBobbing from mod (unknown),pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:tombstone.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:sodium-common.mixins.json:features.gui.hooks.console.GameRendererMixin from mod (unknown),pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod (unknown),pl:mixin:APP:konkrete.neoforge.mixins.json:client.MixinGameRenderer from mod (unknown),pl:mixin:APP:darkmodeeverywhere.mixins.json:GameRenderMixin from mod (unknown),pl:mixin:APP:mixins.artifacts.common.json:ability.nightvision.client.GameRendererMixin from mod (unknown),pl:mixin:APP:justzoom.mixins.json:client.MixinGameRenderer from mod (unknown),pl:mixin:APP:rarcompat.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:flickerfix.mixins.json:MixinGameRenderer from mod (unknown),pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer from mod (unknown),pl:mixin:APP:eternal_starlight-common.mixins.json:client.GameRendererMixin from mod (unknown),pl:mixin:APP:ars_nouveau.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:kubejs.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinGameRenderer_NightVisionCompat from mod (unknown),pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin from mod (unknown),pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.wrapOperation$cdd000$konkrete$wrapRenderScreen_Konkrete(GameRenderer.java:5795) ~[client-1.21.1-20240808.144430-srg.jar%230!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:auroras.mixins.json:client.GameRendererMixin from mod (unknown),pl:mixin:APP:mixins.iris.json:GameRendererAccessor from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinGameRenderer from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinModelViewBobbing from mod (unknown),pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:tombstone.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:sodium-common.mixins.json:features.gui.hooks.console.GameRendererMixin from mod (unknown),pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod (unknown),pl:mixin:APP:konkrete.neoforge.mixins.json:client.MixinGameRenderer from mod (unknown),pl:mixin:APP:darkmodeeverywhere.mixins.json:GameRenderMixin from mod (unknown),pl:mixin:APP:mixins.artifacts.common.json:ability.nightvision.client.GameRendererMixin from mod (unknown),pl:mixin:APP:justzoom.mixins.json:client.MixinGameRenderer from mod (unknown),pl:mixin:APP:rarcompat.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:flickerfix.mixins.json:MixinGameRenderer from mod (unknown),pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer from mod (unknown),pl:mixin:APP:eternal_starlight-common.mixins.json:client.GameRendererMixin from mod (unknown),pl:mixin:APP:ars_nouveau.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:kubejs.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinGameRenderer_NightVisionCompat from mod (unknown),pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin from mod (unknown),pl:mixin:A,pl:runtimedistcleaner:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1092) ~[client-1.21.1-20240808.144430-srg.jar%230!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:auroras.mixins.json:client.GameRendererMixin from mod (unknown),pl:mixin:APP:mixins.iris.json:GameRendererAccessor from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinGameRenderer from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinModelViewBobbing from mod (unknown),pl:mixin:APP:supplementaries-common.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:tombstone.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:sodium-common.mixins.json:features.gui.hooks.console.GameRendererMixin from mod (unknown),pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer from mod (unknown),pl:mixin:APP:konkrete.neoforge.mixins.json:client.MixinGameRenderer from mod (unknown),pl:mixin:APP:darkmodeeverywhere.mixins.json:GameRenderMixin from mod (unknown),pl:mixin:APP:mixins.artifacts.common.json:ability.nightvision.client.GameRendererMixin from mod (unknown),pl:mixin:APP:justzoom.mixins.json:client.MixinGameRenderer from mod (unknown),pl:mixin:APP:rarcompat.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:flickerfix.mixins.json:MixinGameRenderer from mod (unknown),pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer from mod (unknown),pl:mixin:APP:eternal_starlight-common.mixins.json:client.GameRendererMixin from mod (unknown),pl:mixin:APP:ars_nouveau.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:kubejs.mixins.json:GameRendererMixin from mod (unknown),pl:mixin:APP:mixins.iris.json:MixinGameRenderer_NightVisionCompat from mod (unknown),pl:mixin:APP:securitycraft.mixins.json:camera.GameRendererMixin from mod (unknown),pl:mixin:A,pl:runtimedistcleaner:A}
	... 12 more
```

**Comment by LuziferSenpai** [comment]
Yea, got the same error.
Even a other mod author pointed it out.

https://github.com/GlodBlock/ExtendedAE/issues/329

**Comment by MrCrayfish** [comment]
Thanks for the report. Fixed in cf7bb56b00ae3aeb4c7bce60b7f1848e316ababc
